# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ExploreMine' do
  
  pod 'Alamofire'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'SwiftyJSON'
  pod 'SDWebImage'
  pod 'IQKeyboardManagerSwift'
  
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for ExploreMine
  
end
